CREATE TABLE IF NOT EXISTS employees_clean (
    employee_id INTEGER PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    full_name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    email_domain VARCHAR(50),
    hire_date DATE,
    job_title VARCHAR(100),
    department VARCHAR(50),
    salary DOUBLE PRECISION,
    salary_band VARCHAR(20),
    manager_id INTEGER,
    address TEXT,
    city VARCHAR(50),
    state VARCHAR(10),
    zip_code VARCHAR(10),
    birth_date DATE,
    age INTEGER,
    tenure_years INTEGER,
    status VARCHAR(20) DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);